title: Machine Learning
logo: /assets/img/logo.png
description: Courses by Dr. Balaji Srinivasan and Dr. Ganapathy Krishnamurthy, IITM.
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
